//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public class Sign_in
    {
        [DisplayName("單位")]
        [Required]
        public string usr_index { get; set; }

        [DisplayName("帳號")]
        [Required]
        public string usr_name { get; set; }

        [DisplayName("密碼")]
        [Required]
        public string usr_key { get; set; }

        [DisplayName("職業1")]
        public string post1 { get; set; }

        [DisplayName("職業2")]
        public string post2 { get; set; }
    }
}
